version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest 
    steps:
      - checkout
      - run:
          name: List Files After Checkout
          command: ls -al
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:  
    docker:    
      - image: google/cloud-sdk:alpine  
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Set Working Directory
          command: cd .
      - run:        
          name: Create Service Key File        
          command: echo "$GCLOUD_SERVICE_KEY" > $HOME/gcloud-service-key.json          
      - run:
          name: Authenticate Google Cloud        
          command: |          
            gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json          
            gcloud config set project $GOOGLE_PROJECT_ID

      - run:
          name: Check if App Engine API is enabled
          command: |
            if ! gcloud services list --enabled --format='value(NAME)' | grep -q appengine.googleapis.com; then
            echo "Error: App Engine API is not enabled. Please enable it in the Google Cloud Console."
            echo "Visit: https://console.developers.google.com/apis/api/appengine.googleapis.com/overview?project=$GOOGLE_PROJECT_ID"
            exit 1
            fi
      - run:
          name: List Files After Moving app.yaml
          command: ls -al

      - run:
          name: Deploy Application
          command: gcloud app deploy yaml/app.yaml --project $GOOGLE_PROJECT_ID --quiet --verbosity=debug


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build